### ISSUE TITLE
No issue 

### ISSUE THREAD

**Issue by ebranch** [cytech/BillingTrack#4] opened 2019-05-18 16:01 UTC
How do you start BillingTrack/setup?

**Comment by cytech** [comment] 2019-05-19 13:48
http://YOUR_BILLINGTRACK_WEBSITE/setup

**Comment by cytech** [comment] 2019-05-31 19:03
Closed as a duplicate of https://github.com/cytech/BillingTrack/issues/5

**Closed by cytech** 2019-05-31 19:03 UTC
